version: "3.1"

services:
  db:
    image: postgres
    restart: always
    container_name: "pgsql"
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
    ports:
        - 5432:5432
